<?php if ($block->getIsFormEnabled()):?> 
<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post"   action="<?php echo $block->getFormAction(); ?>">
            <fieldset class="fieldset">
                <legend class="legend"><span><?php echo 'Fill Detail' ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?php echo 'Name' ?></span></label>
                            <div class="control">
                                <input name="name" id="Name" title="Name" value="" class="input-text" type="text">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?php echo 'Date' ?></span></label>
                            <div class="control">
                                <input name="date" id="date" title="date" class="input-text" type="date">
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?php echo 'Save'?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>
<?php else: ?>
    <p><em>Form not enabled</em></p>
<?php endif; ?>


<!-- 
<?php if ($block->getIsFormEnabled()): ?> 
<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post"   action="<?php echo $block->getFormAction(); ?>">
            <fieldset class="fieldset">
                <legend class="legend"><span><?php echo 'Fill Detail' ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?php echo 'Name' ?></span></label>
                            <div class="control">
                                <input name="name" id="Name" title="Name" value="" class="input-text" type="text">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?php echo 'Date' ?></span></label>
                            <div class="control">
                                <input name="date" id="date" title="date" class="input-text" type="date">
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?php echo 'Save'?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>
<?php else: ?>
    <p><em>Form not enabled</em></p>
<?php endif; ?>

-->
